In [3]:
import numpy as np

In [4]:
np.random.seed(55)
a=np.random.randint(30,99,20)
a

array([56, 69, 59, 91, 85, 67, 63, 84, 65, 76, 91, 42, 54, 61, 81, 30, 85,
       92, 73, 79])

In [5]:
a[-1]

79

In [6]:
a[0]

56

In [7]:
a.ndim

1

In [8]:
9a[19]

79

In [9]:
b=np.random.randint(20,80,(8,9))
b

array([[44, 68, 34, 76, 30, 79, 79, 48, 61],
       [64, 44, 72, 49, 64, 41, 33, 72, 61],
       [78, 53, 65, 44, 38, 36, 65, 75, 47],
       [38, 76, 62, 52, 73, 30, 74, 23, 44],
       [78, 27, 38, 21, 39, 65, 73, 50, 39],
       [30, 45, 22, 44, 52, 33, 55, 31, 54],
       [35, 53, 62, 54, 68, 79, 41, 40, 23],
       [27, 40, 33, 54, 36, 60, 39, 46, 34]])

In [10]:
b.shape

(8, 9)

In [11]:
b[2:6:1,1:7:2]

array([[53, 44, 36],
       [76, 52, 30],
       [27, 21, 65],
       [45, 44, 33]])

In [12]:
b.ndim

2

In [13]:
b[7,0]

27

In [ ]:
array[row_start: row_end : row_step , col_start: col_end:col_step]

In [15]:
import pandas as pd

In [26]:
k=[[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [27]:
np.array(k)

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [28]:
pd.Series(k)

0      [4, 7]
1      [2, 9]
2      [7, 3]
3    [90, 50]
dtype: object

In [29]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [30]:
t.ndim

2

In [32]:
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [33]:
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [34]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [37]:
df=pd.DataFrame(t,columns=['name','sub'],index=[289,290,291,292])
df

name  sub
289     4    7
290     2    9
291     7    3
292    90   50

In [38]:
df.columns

Index(['name', 'sub'], dtype='object')

In [39]:
df['sub']

289     7
290     9
291     3
292    50
Name: sub, dtype: int32

In [40]:
df['sub'].mean()

17.25

In [41]:
df['sub'].median()

8.0

In [42]:
df['sub'].mode()

0     3
1     7
2     9
3    50
Name: sub, dtype: int32

In [43]:
df['sub'].var()

482.9166666666667

In [44]:
df['sub'].std()

21.975364995072702

In [45]:
df['sub'].min()

3

In [46]:
df['sub'].max()

50

In [48]:
df['sub'].quantile(0.25)

6.0

In [49]:
df['sub'].quantile(0.75)

19.25